---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./csidriverconfigs.yaml
  - ./sandboxconfigs.yaml
  - ./workerpools.yaml
  - ./sandboxconfig-validation.yaml
