---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chat-ui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: chat-ui
  values:
    controllers:
      chat-ui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/huggingface/chat-ui
              tag: latest@sha256:1cdfd271535842fea85f93742b995836396b7211fc1c2180f2a3e7f953050199
            env:
              TZ: Europe/Rome
              PORT: &port 3000
              MONGO_STORAGE_PATH: /data/db
              OPENAI_BASE_URL: http://litellm.ai.svc.cluster.local:4000/v1
              OPENAI_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: litellm
                    key: LITELLM_MASTER_KEY
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - chat-ui.labx.sh
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data/db
