---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  chartRef:
    kind: OCIRepository
    name: n8n
  interval: 1h
  values:
    controllers:
      n8n:
        containers:
          app:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 2.30.3@sha256:4e9de05de2f87c34774d71a93dd9aca924adb930c4c7f2f7797b84fa93327be5
            env:
              N8N_PORT: &port 5678
              N8N_HOST: &host "n8n.labx.sh"
              N8N_PROTOCOL: https
              N8N_EDITOR_BASE_URL: &url "https://n8n.labx.sh/"
              N8N_RUNNERS_ENABLED: "true"
              N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
              N8N_PROXY_HOPS: 1
              N8N_USER_FOLDER: /data
              WEBHOOK_URL: *url
              GENERIC_TIMEZONE: Europe/Rome
              TZ: Europe/Rome
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: *port
    route:
      app:
        hostnames:
          - *host
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
      tmp:
        type: emptyDir
