# yaml-language-server: $schema=https://k8s-schemas-jnobrega.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openshell
spec:
  chartRef:
    kind: OCIRepository
    name: openshell
  interval: 1h
  values:
    certManager:
      enabled: true
    grpcRoute:
      enabled: true
      hostnames:
        - openshell.labx.sh
      gateway:
        name: envoy-internal
        namespace: network
    server:
      auth:
        allowUnauthenticatedUsers: true
