router bgp 64513
  bgp router-id 10.0.10.1

  no bgp default ipv4-unicast
  no bgp ebgp-requires-policy

  neighbor k8s-v4 peer-group
  neighbor k8s-v4 remote-as 64514

  neighbor 10.0.30.21 peer-group k8s-v4
  neighbor 10.0.30.22 peer-group k8s-v4

  neighbor k8s-v4 soft-reconfiguration inbound

  address-family ipv4 unicast
    neighbor k8s-v4 activate
    neighbor k8s-v4 next-hop-self
  exit-address-family
exit