---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: substrate-crds
spec:
  interval: 1h
  path: ./kubernetes/apps/ate-system/substrate/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ate-system
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: substrate
spec:
  dependsOn:
    - name: substrate-crds
  interval: 1h
  path: ./kubernetes/apps/ate-system/substrate/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ate-system
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: substrate-postgres-env
spec:
  dependsOn:
    - name: substrate-postgres
  interval: 1h
  path: ./kubernetes/apps/ate-system/substrate/env
  postBuild:
    substituteFrom:
      - kind: Secret
        name: substrate-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ate-system
  wait: true
