---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
spec:
  chartRef:
    kind: OCIRepository
    name: kagent-crds
  interval: 1h
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
spec:
  chartRef:
    kind: OCIRepository
    name: kagent
  interval: 1h
  dependsOn:
    - name: kagent-crds
  values:
    grafana-mcp: { enabled: false }
    kagent-tools: { enabled: false }
    k8s-agent: { enabled: false }
    kgateway-agent: { enabled: false }
    istio-agent: { enabled: false }
    promql-agent: { enabled: false }
    observability-agent: { enabled: false }
    argo-rollouts-agent: { enabled: false }
    helm-agent: { enabled: false }
    cilium-policy-agent: { enabled: false }
    cilium-manager-agent: { enabled: false }
    cilium-debug-agent: { enabled: false }

    controller:
      env:
        - name: OPENSHELL_GATEWAY_URL
          value: openshell.ai.svc.cluster.local:8080
        - name: OPENSHELL_INSECURE
          value: "true"
    ui:
      replicas: 0
    database:
      postgres:
        bundled:
          enabled: true
          storageClassName: ceph-block
          storage: 1Gi
    providers:
      default: openAI
      openAI:
        provider: OpenAI
        apiKeySecretRef: kagent
        apiKeySecretKey: BIFROST_API_KEY
        config:
          baseUrl: "http://bifrost.ai.svc.cluster.local:8080/openai/v1"
