---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docling
spec:
  chartRef:
    kind: OCIRepository
    name: docling
  interval: 1h
  values:
    controllers:
      docling:
        containers:
          app:
            image:
              repository: ghcr.io/docling-project/docling-serve-cpu
              tag: v1.26.0@sha256:7e07522e0240c1db3ff5b837ffa969c2ecd5a71664c0e0369f5a69fc169e30ba
            env:
              TZ: Europe/Rome
              OMP_NUM_THREADS: 8
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 5001
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                memory: 2Gi
              limits:
                memory: 4Gi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimName: shared
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      run:
        type: emptyDir
        medium: Memory
        sizeLimit: 16Mi
      tmp:
        type: emptyDir
