---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docling
spec:
  chartRef:
    kind: OCIRepository
    name: docling
  interval: 1h
  values:
    controllers:
      docling:
        containers:
          app:
            image:
              repository: ghcr.io/marcocondrache/docling-serve-rocm
              tag: 1.26.0@sha256:cf692f456e9c16ad9c82f8f4f23eb740f6c90ba68b9d3b7c64319930e6a74d80
            env:
              TZ: Europe/Rome
              DOCLING_NUM_THREADS: 8
              HSA_OVERRIDE_GFX_VERSION: 11.0.0
              TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL: 1
              MIOPEN_USER_DB_PATH: /opt/app-root/src/.cache/miopen
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 5001
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              claims:
                - name: gpu
              requests:
                cpu: 8
                memory: 2Gi
              limits:
                memory: 4Gi
    defaultPodOptions:
      resourceClaims:
        - name: gpu
          resourceClaimName: shared
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      cache:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /opt/app-root/src/.cache/miopen
            subPath: miopen
          - path: /opt/app-root/src/.cache/torch
            subPath: torch
      run:
        type: emptyDir
        medium: Memory
        sizeLimit: 16Mi
      tmp:
        type: emptyDir
