---
apiVersion: agents.x-k8s.io/v1beta1
kind: Sandbox
metadata:
  name: open-terminal
spec:
  service: true
  podTemplate:
    spec:
      runtimeClassName: gvisor
      securityContext:
        fsGroup: 1000
      containers:
        - name: open-terminal
          image: ghcr.io/open-webui/open-terminal:latest@sha256:3af1a1aab49d653d357a5176c9862af0111ccf4b8b3a5f2bbdef109f196aeca7
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: TZ
              value: Europe/Rome
          envFrom:
            - secretRef:
                name: open-terminal-secret
          volumeMounts:
            - name: home
              mountPath: /home/user
  volumeClaimTemplates:
    - metadata:
        name: home
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: miroir-local
        resources:
          requests:
            storage: 10Gi
