---
apiVersion: agents.x-k8s.io/v1beta1
kind: Sandbox
metadata:
  name: hermes-agent
spec:
  podTemplate:
    metadata:
      labels:
        app: hermes
    spec:
      containers:
        - name: hermes
          image: docker.io/nousresearch/hermes-agent:v2026.7.7.2@sha256:9c841866021c54c4596849f6135717e8a4d52ba510b7f52c50aef1de1a283973
          args: ["gateway", "run"]
          envFrom:
            - secretRef:
                name: hermes-secret
          env:
            - name: HERMES_DASHBOARD
              value: "1"
            - name: HERMES_DASHBOARD_HOST
              value: "0.0.0.0"
            - name: API_SERVER_ENABLED
              value: "true"
          ports:
            - containerPort: 8642
              name: api
            - containerPort: 9119
              name: dashboard
          volumeMounts:
            - name: data
              mountPath: /opt/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hermes
