---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bichon
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bichon
  values:
    controllers:
      bichon:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/rustmailer/bichon
              tag: 1.6.2@sha256:9a81f55be71ceba4979f4d7ce06a82fee860cf3177b50385abf0ff893bb3c53e
            env:
              TZ: Europe/Rome
              BICHON_HTTP_PORT: &port 15630
              BICHON_ROOT_DIR: /data
              BICHON_PUBLIC_URL: https://bichon.labx.sh
              BICHON_ENCRYPT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-secret"
                    key: BICHON_ENCRYPT_PASSWORD
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - bichon.labx.sh
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /data
