---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gpu-dra-driver
spec:
  chartRef:
    kind: OCIRepository
    name: k8s-gpu-dra-driver
  interval: 1h
  values:
    cdi:
      dynamicPath: /run/cdi
