---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gpu-dra-driver
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.0.1
  url: oci://ocharted.labx.sh/rocm.github.io/k8s-gpu-dra-driver/k8s-gpu-dra-driver
