---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: papra
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: papra
  values:
    controllers:
      papra:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/papra-hq/papra
              tag: 26.6.0-rootless
            env:
              PORT: &port 8000
              APP_BASE_URL: https://papra.labx.sh
              DOCUMENTS_OCR_LANGUAGES: eng,ita,ron
              INGESTION_FOLDER_IS_ENABLED: true
              INGESTION_FOLDER_POST_PROCESSING_STRATEGY: delete
              INGESTION_FOLDER_PROCESSING_CONCURRENCY: 4
              AUTH_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-secret"
                    key: PAPRA_SECRET
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [3000]
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - papra.labx.sh
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /app/app-data
