---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  chartRef:
    kind: OCIRepository
    name: open-webui
  interval: 30m
  values:
    workload:
      kind: Deployment
    image:
      tag: v0.10.2-slim@sha256:f03f7fcdaf5e3381b3d505c0e66f2bf4e82d1918082022b85dee7da1299b6efd
    ollama:
      enabled: false
    pipelines:
      enabled: false
    enableOpenaiApi: false
    websocket:
      enabled: false
    extraEnvVars:
      OFFLINE_MODE: true
      ENABLE_SIGNUP: false
    extraEnvFrom:
      - secretRef:
          name: open-webui-secret
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 2Gi
    persistence:
      enabled: true
      existingClaim: open-webui
    route:
      enabled: true
      hostnames:
        - chat.labx.sh
      parentRefs:
        - name: envoy-internal
          namespace: network
