---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bifrost
    template:
      data:
        BIFROST_ENCRYPTION_KEY: "{{ .BIFROST_ENCRYPTION_KEY }}"
        MINIMAX_API_KEY: "{{ .MINIMAX_API_KEY }}"
        NEURALWATT_API_KEY: "{{ .NEURALWATT_API_KEY }}"
        CONTEXT7_API_KEY: "{{ .CONTEXT7_API_KEY }}"
  dataFrom:
    - extract:
        key: bifrost
    - extract:
        key: minimax
    - extract:
        key: neuralwatt
    - extract:
        key: context7
