---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bifrost
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bifrost
    template:
      data:
        BIFROST_ENCRYPTION_KEY: "{{ .BIFROST_ENCRYPTION_KEY }}"
        BIFROST_ADMIN_USERNAME: "{{ .BIFROST_ADMIN_USERNAME }}"
        BIFROST_ADMIN_PASSWORD: "{{ .BIFROST_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: bifrost
