---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bifrost
spec:
  chartRef:
    kind: OCIRepository
    name: bifrost
  interval: 1h
  values:
    image:
      repository: mirror.gcr.io/maximhq/bifrost
      tag: 2.1.27@sha256:67118ca0c5599e873a82618d22176eec699ada3a8cf4ca1aeb8ad8001dd80a59

    podSecurityContext:
      runAsUser: 1000

    storage:
      mode: sqlite
      persistence:
        enabled: true
        storageClass: ceph-block
    bifrost:
      host: "::"
      encryptionKeySecret:
        name: bifrost
        key: BIFROST_ENCRYPTION_KEY
