---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lubelogger
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: lubelogger
  values:
    controllers:
      lubelogger:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hargata/lubelogger
              tag: v1.6.9@sha256:c8f0bfd48b62be4757f03c94267d74f11c79bb0a76595fe4d02dc97ea9b8b5fa
            env:
              TZ: Europe/Rome
              LUBELOGGER_PORT: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.labx.sh"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          lubelogger:
            app:
              - path: /App/data
                subPath: data
              - path: /root/.aspnet/DataProtection-Keys
                subPath: keys
